
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin/"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Library/PostgreSQL/14/bin/"
      - "/Library/PostgreSQL/*/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.10/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/anniewang/.dotnet/tools/"
      - "/Users/anniewang/miniconda3/bin/"
      - "/Users/anniewang/miniconda3/condabin/"
      - "/Users/anniewang/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin/"
    searched_directories:
      - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin/uname"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/uname"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Library/PostgreSQL/14/bin/uname"
      - "/Library/PostgreSQL/*/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.10/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/PostgreSQL/14/bin"
        - "/Library/PostgreSQL/*/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.10/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin"
        - "/Users/anniewang/miniconda3/bin"
        - "/Users/anniewang/miniconda3/condabin"
        - "/Users/anniewang/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin"
        - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin/"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Library/PostgreSQL/14/bin/"
      - "/Library/PostgreSQL/*/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.10/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/anniewang/.dotnet/tools/"
      - "/Users/anniewang/miniconda3/bin/"
      - "/Users/anniewang/miniconda3/condabin/"
      - "/Users/anniewang/Library/Application Support/JetBrains/Toolbox/scripts/"
      - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin/"
    searched_directories:
      - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin/install_name_tool"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/install_name_tool"
      - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Library/PostgreSQL/14/bin/install_name_tool"
      - "/Library/PostgreSQL/*/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.10/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Library/PostgreSQL/14/bin"
        - "/Library/PostgreSQL/*/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.10/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
        - "/Users/anniewang/Library/Application Support/Code/User/globalStorage/github.copilot-chat/copilotCli"
        - "/Users/anniewang/.nvm/versions/node/v20.8.1/bin"
        - "/Users/anniewang/miniconda3/bin"
        - "/Users/anniewang/miniconda3/condabin"
        - "/Users/anniewang/Library/Application Support/JetBrains/Toolbox/scripts"
        - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin"
        - "/Users/anniewang/mongodb-macos-aarch64-8.0.4/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
